// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Rz5Sh4EUTxR--zNOzxwcmUXWpA4IF9k',
    appId: '1:726471516335:web:2e99ca5cef8c63546b745a',
    messagingSenderId: '726471516335',
    projectId: 'onee-6f1a0',
    authDomain: 'onee-6f1a0.firebaseapp.com',
    storageBucket: 'onee-6f1a0.appspot.com',
    measurementId: 'G-CZF4Q9LL66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCntsHSPUAMTMahjzXJuG_ATvFBQiyo_5c',
    appId: '1:726471516335:android:f8af2115316d761a6b745a',
    messagingSenderId: '726471516335',
    projectId: 'onee-6f1a0',
    storageBucket: 'onee-6f1a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTstk-m3eKfrq41iqE0by60bYXvkiYFPw',
    appId: '1:726471516335:ios:60e151922c5ed3c86b745a',
    messagingSenderId: '726471516335',
    projectId: 'onee-6f1a0',
    storageBucket: 'onee-6f1a0.appspot.com',
    iosBundleId: 'com.example.one',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTstk-m3eKfrq41iqE0by60bYXvkiYFPw',
    appId: '1:726471516335:ios:60e151922c5ed3c86b745a',
    messagingSenderId: '726471516335',
    projectId: 'onee-6f1a0',
    storageBucket: 'onee-6f1a0.appspot.com',
    iosBundleId: 'com.example.one',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Rz5Sh4EUTxR--zNOzxwcmUXWpA4IF9k',
    appId: '1:726471516335:web:5fc23681494ed3266b745a',
    messagingSenderId: '726471516335',
    projectId: 'onee-6f1a0',
    authDomain: 'onee-6f1a0.firebaseapp.com',
    storageBucket: 'onee-6f1a0.appspot.com',
    measurementId: 'G-BQY3HYFPZP',
  );
}
